on: 
  push: 
    branch:
      -main

jobs:
  build:
    name: build app
    runs-on: ubuntu-latest
    steps:
      - name: menampilkan teks
        run: echo "ini step build"
  test:
    name: test app
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: menampilkan teks
        run: echo "ini step test"
  deployment:
    name: deploy app
    runs-on: ubuntu-latest
    needs: test
    steps:
         name: remote ssh command
    on: [push]
    jobs:
      build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v1.2.0
          with:
            host: ${{ secrets.HOST }}
            username: vegakun.io
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            script: whoami
              script: |
                rm -rf /var/www/html/*
                rm -rf /var/www/html/.git
                rm -rf /var/www/html/.github
                git clone https://github.com/Ray2Buzter/Vegakun /var/www/html/
      
